/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.charlware.rocketlauncher.ui;

import com.charlware.rocketlauncher.Command;
import com.charlware.rocketlauncher.FaceTracker;
import com.charlware.rocketlauncher.RocketLauncher;
import com.charlware.rocketlauncher.device.DreamCheeky;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author charlvj
 */
public class ControlPanel extends javax.swing.JFrame {

    private RocketLauncher rocketLauncher;
    private Webcam webcam;
    private WebcamPanel panel = null;
    private Executor executor = Executors.newSingleThreadExecutor();
    private FaceTracker faceTracker;
    private boolean enableFaceTracker = false;

    /**
     * Creates new form ControlPanel
     */
    public ControlPanel() {

        rocketLauncher = new RocketLauncher(new DreamCheeky());
        rocketLauncher.open();
        
        webcam = Webcam.getDefault();
        if (webcam != null) {
            System.out.println("Webcam: " + webcam.getName());
            
            faceTracker = new FaceTracker(rocketLauncher, webcam);
            if(enableFaceTracker) {
                executor.execute(faceTracker);
            }
            
            panel = new WebcamPanel(webcam);
            panel.setFPSDisplayed(true);
            panel.setDisplayDebugInfo(true);
            panel.setImageSizeDisplayed(true);
//            panel.setMirrored(true);
            panel.setPainter(new WebcamPanelPainter(webcam, panel, faceTracker));

        } else {
            System.out.println("No webcam detected");
        }        
        
        
        initComponents();
        if(panel != null) {
            pnWebcam.add(panel, BorderLayout.CENTER);
        }
        pack();
        setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        btUp = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btLeft = new javax.swing.JButton();
        btFire = new javax.swing.JButton();
        btRight = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        btDown = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        pnWebcam = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        jButton2.setEnabled(false);
        jPanel1.add(jButton2);

        btUp.setText("Up");
        btUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btUpMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btUpMouseReleased(evt);
            }
        });
        btUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUpActionPerformed(evt);
            }
        });
        jPanel1.add(btUp);

        jButton5.setEnabled(false);
        jPanel1.add(jButton5);

        btLeft.setText("Left");
        btLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btLeftMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btLeftMouseReleased(evt);
            }
        });
        jPanel1.add(btLeft);

        btFire.setText("Fire!");
        btFire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btFireMouseClicked(evt);
            }
        });
        jPanel1.add(btFire);

        btRight.setText("Right");
        btRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btRightMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btRightMouseReleased(evt);
            }
        });
        jPanel1.add(btRight);

        jButton9.setEnabled(false);
        jPanel1.add(jButton9);

        btDown.setText("Down");
        btDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btDownMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btDownMouseReleased(evt);
            }
        });
        jPanel1.add(btDown);

        jButton6.setEnabled(false);
        jPanel1.add(jButton6);

        getContentPane().add(jPanel1);

        pnWebcam.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnWebcam);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUpActionPerformed

    private void btUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpMousePressed
        rocketLauncher.sendCommand(Command.UP);
    }//GEN-LAST:event_btUpMousePressed

    private void btUpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUpMouseReleased
        rocketLauncher.sendCommand(Command.STOP);
    }//GEN-LAST:event_btUpMouseReleased

    private void btDownMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDownMousePressed
        rocketLauncher.sendCommand(Command.DOWN);
    }//GEN-LAST:event_btDownMousePressed

    private void btDownMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDownMouseReleased
        rocketLauncher.sendCommand(Command.STOP);
    }//GEN-LAST:event_btDownMouseReleased

    private void btLeftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLeftMousePressed
        rocketLauncher.sendCommand(Command.LEFT);
    }//GEN-LAST:event_btLeftMousePressed

    private void btLeftMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLeftMouseReleased
        rocketLauncher.sendCommand(Command.STOP);
    }//GEN-LAST:event_btLeftMouseReleased

    private void btRightMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRightMousePressed
        rocketLauncher.sendCommand(Command.RIGHT);
    }//GEN-LAST:event_btRightMousePressed

    private void btRightMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btRightMouseReleased
        rocketLauncher.sendCommand(Command.STOP);
    }//GEN-LAST:event_btRightMouseReleased

    private void btFireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btFireMouseClicked
        rocketLauncher.sendCommand(Command.FIRE);
    }//GEN-LAST:event_btFireMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            rocketLauncher.close();
            webcam.close();
        } catch (IOException ex) {
            Logger.getLogger(ControlPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDown;
    private javax.swing.JButton btFire;
    private javax.swing.JButton btLeft;
    private javax.swing.JButton btRight;
    private javax.swing.JButton btUp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnWebcam;
    // End of variables declaration//GEN-END:variables
}
